//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Acc_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class A4Print
    {
        public string GROUP_GUID { get; set; }
        public Nullable<int> NUMBER { get; set; }
        public Nullable<System.Guid> PARENT_GUID { get; set; }
        public Nullable<System.Guid> CUST { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public Nullable<double> disc { get; set; }
        public Nullable<double> EXTEA { get; set; }
        public Nullable<double> p_disc { get; set; }
        public Nullable<double> p_extra { get; set; }
        public Nullable<double> Total { get; set; }
        public Nullable<double> type_dis { get; set; }
        public Nullable<double> disc_rate { get; set; }
        public string type_pay { get; set; }
        public string CUSTOMER_NAME { get; set; }
        public Nullable<int> CUSTOMER_MOBILE1 { get; set; }
        public string CUSTOMER_MOBILE2 { get; set; }
        public Nullable<double> CUSTOMER_COMPANY { get; set; }
        public string CUSTOMER_PHON { get; set; }
        public string CUSTOMER_EMAIL { get; set; }
        public Nullable<double> CUSTOMER_STREET { get; set; }
        public Nullable<System.DateTime> time_bill { get; set; }
        public Nullable<double> Cash { get; set; }
        public Nullable<double> KNET { get; set; }
        public string NAME { get; set; }
        public Nullable<double> QTY { get; set; }
        public Nullable<double> PRICE { get; set; }
        public string NOTE { get; set; }
        public Nullable<double> Item_Discount { get; set; }
        public Nullable<double> extra { get; set; }
        public string unit { get; set; }
        public Nullable<double> qty_unit { get; set; }
        public string barcode { get; set; }
        public Nullable<double> VAT { get; set; }
        public string delivery_mobile { get; set; }
        public byte[] image { get; set; }
        public string Bill_Name { get; set; }
        public Nullable<int> DELETE_NUM { get; set; }
        public Nullable<int> manual_number { get; set; }
        public string delivery_customer { get; set; }
        public string Branch { get; set; }
        public Nullable<System.DateTime> Booking_Time { get; set; }
        public Nullable<System.Guid> TRAN_POS_GUID { get; set; }
        public Nullable<System.DateTime> Booking_Date { get; set; }
        public Nullable<int> car_current_counter { get; set; }
        public Nullable<double> TRAN_POS_PAY { get; set; }
        public string Header_Note { get; set; }
        public int id { get; set; }
        public Nullable<int> SN { get; set; }
        public string TAF { get; set; }
        public string user_name { get; set; }
        public string Waiter { get; set; }
    }
}
