//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Acc_App.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_ACCEntities : DbContext
    {
        public DB_ACCEntities()
            : base("name=DB_ACCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__EFMigrationsHistory> C__EFMigrationsHistory { get; set; }
        public virtual DbSet<ACCOUNT> ACCOUNT { get; set; }
        public virtual DbSet<Appointment> Appointment { get; set; }
        public virtual DbSet<Approval> Approval { get; set; }
        public virtual DbSet<AREA> AREA { get; set; }
        public virtual DbSet<Authors> Authors { get; set; }
        public virtual DbSet<b1> b1 { get; set; }
        public virtual DbSet<b2> b2 { get; set; }
        public virtual DbSet<BANK_DEPOSIT> BANK_DEPOSIT { get; set; }
        public virtual DbSet<BILL1> BILL1 { get; set; }
        public virtual DbSet<BILL2> BILL2 { get; set; }
        public virtual DbSet<Booking_Details> Booking_Details { get; set; }
        public virtual DbSet<Books> Books { get; set; }
        public virtual DbSet<branch> branch { get; set; }
        public virtual DbSet<Brand> Brand { get; set; }
        public virtual DbSet<CAR_CARD> CAR_CARD { get; set; }
        public virtual DbSet<car_check_prices> car_check_prices { get; set; }
        public virtual DbSet<CASH_DAY> CASH_DAY { get; set; }
        public virtual DbSet<CATEGORY> CATEGORY { get; set; }
        public virtual DbSet<check_car> check_car { get; set; }
        public virtual DbSet<CLASS_> CLASS_ { get; set; }
        public virtual DbSet<Config> Config { get; set; }
        public virtual DbSet<contract> contract { get; set; }
        public virtual DbSet<COUNTRY> COUNTRY { get; set; }
        public virtual DbSet<CURRENCY> CURRENCY { get; set; }
        public virtual DbSet<customer> customer { get; set; }
        public virtual DbSet<Customer_Branch> Customer_Branch { get; set; }
        public virtual DbSet<Day_Student> Day_Student { get; set; }
        public virtual DbSet<DAY1> DAY1 { get; set; }
        public virtual DbSet<DAY2> DAY2 { get; set; }
        public virtual DbSet<Deleted_items> Deleted_items { get; set; }
        public virtual DbSet<DELIVERY_CUSTOMERS> DELIVERY_CUSTOMERS { get; set; }
        public virtual DbSet<doctor> doctor { get; set; }
        public virtual DbSet<Driver> Driver { get; set; }
        public virtual DbSet<EMPLOYEE> EMPLOYEE { get; set; }
        public virtual DbSet<EMPLOYEE_LEARN> EMPLOYEE_LEARN { get; set; }
        public virtual DbSet<Expenses_Category> Expenses_Category { get; set; }
        public virtual DbSet<Genders> Genders { get; set; }
        public virtual DbSet<GROUPS> GROUPS { get; set; }
        public virtual DbSet<hindering> hindering { get; set; }
        public virtual DbSet<HR_Emp_Card> HR_Emp_Card { get; set; }
        public virtual DbSet<HR_JOB_NAMES> HR_JOB_NAMES { get; set; }
        public virtual DbSet<iteme> iteme { get; set; }
        public virtual DbSet<JOB> JOB { get; set; }
        public virtual DbSet<JOBE_MPLOYEE> JOBE_MPLOYEE { get; set; }
        public virtual DbSet<LEARNING> LEARNING { get; set; }
        public virtual DbSet<Main_Discount> Main_Discount { get; set; }
        public virtual DbSet<ORDER_HISTORY> ORDER_HISTORY { get; set; }
        public virtual DbSet<order_types> order_types { get; set; }
        public virtual DbSet<Order1> Order1 { get; set; }
        public virtual DbSet<Order2> Order2 { get; set; }
        public virtual DbSet<PATH_M> PATH_M { get; set; }
        public virtual DbSet<personal> personal { get; set; }
        public virtual DbSet<POS_CUSTOMERS> POS_CUSTOMERS { get; set; }
        public virtual DbSet<POS_CUSTOMERS_GROUP> POS_CUSTOMERS_GROUP { get; set; }
        public virtual DbSet<POS_Expenses> POS_Expenses { get; set; }
        public virtual DbSet<POS_MENU> POS_MENU { get; set; }
        public virtual DbSet<pos_money_receipt> pos_money_receipt { get; set; }
        public virtual DbSet<POS_Shieft> POS_Shieft { get; set; }
        public virtual DbSet<POS_USERS> POS_USERS { get; set; }
        public virtual DbSet<Print_Item> Print_Item { get; set; }
        public virtual DbSet<PROMO_CODE> PROMO_CODE { get; set; }
        public virtual DbSet<Q_CURRENT_QUEUE> Q_CURRENT_QUEUE { get; set; }
        public virtual DbSet<Q_STAFF_DETAILS> Q_STAFF_DETAILS { get; set; }
        public virtual DbSet<RE_Contract> RE_Contract { get; set; }
        public virtual DbSet<RE_Flat> RE_Flat { get; set; }
        public virtual DbSet<Receipt_Design> Receipt_Design { get; set; }
        public virtual DbSet<Recipes> Recipes { get; set; }
        public virtual DbSet<RELATED_ITEMS> RELATED_ITEMS { get; set; }
        public virtual DbSet<SALE_DISCOUNT> SALE_DISCOUNT { get; set; }
        public virtual DbSet<SALES_MAN> SALES_MAN { get; set; }
        public virtual DbSet<SALOUN_SESSIONS> SALOUN_SESSIONS { get; set; }
        public virtual DbSet<Schedual> Schedual { get; set; }
        public virtual DbSet<SERIALNUMBERS> SERIALNUMBERS { get; set; }
        public virtual DbSet<SERVICE_TRANSACTIONS> SERVICE_TRANSACTIONS { get; set; }
        public virtual DbSet<set_pos> set_pos { get; set; }
        public virtual DbSet<SHOW_USE> SHOW_USE { get; set; }
        public virtual DbSet<Staff_Sales_tb> Staff_Sales_tb { get; set; }
        public virtual DbSet<STORE> STORE { get; set; }
        public virtual DbSet<STUDENT> STUDENT { get; set; }
        public virtual DbSet<SUBS_INV> SUBS_INV { get; set; }
        public virtual DbSet<SUBS_TYPE> SUBS_TYPE { get; set; }
        public virtual DbSet<System_Date> System_Date { get; set; }
        public virtual DbSet<Tables> Tables { get; set; }
        public virtual DbSet<TB_END> TB_END { get; set; }
        public virtual DbSet<TEACHER> TEACHER { get; set; }
        public virtual DbSet<Ticket> Ticket { get; set; }
        public virtual DbSet<Ticket_Player> Ticket_Player { get; set; }
        public virtual DbSet<Ticket_License> Ticket_License { get; set; }
        public virtual DbSet<TICKET_O2> TICKET_O2 { get; set; }
        public virtual DbSet<TYPE_BILL> TYPE_BILL { get; set; }
        public virtual DbSet<TYPE_CASH> TYPE_CASH { get; set; }
        public virtual DbSet<UNITS> UNITS { get; set; }
        public virtual DbSet<US00_BT> US00_BT { get; set; }
        public virtual DbSet<US00_ET> US00_ET { get; set; }
        public virtual DbSet<user000> user000 { get; set; }
        public virtual DbSet<AggregatedCounter> AggregatedCounter { get; set; }
        public virtual DbSet<Hash> Hash { get; set; }
        public virtual DbSet<Job1> Job1 { get; set; }
        public virtual DbSet<JobParameter> JobParameter { get; set; }
        public virtual DbSet<JobQueue> JobQueue { get; set; }
        public virtual DbSet<List> List { get; set; }
        public virtual DbSet<Schema> Schema { get; set; }
        public virtual DbSet<Server> Server { get; set; }
        public virtual DbSet<Set> Set { get; set; }
        public virtual DbSet<State> State { get; set; }
        public virtual DbSet<dayee> dayee { get; set; }
        public virtual DbSet<Studints> Studints { get; set; }
        public virtual DbSet<Counter> Counter { get; set; }
        public virtual DbSet<A4Print> A4Print { get; set; }
        public virtual DbSet<Account_Balance> Account_Balance { get; set; }
        public virtual DbSet<Account_Balance2> Account_Balance2 { get; set; }
        public virtual DbSet<Account_Statement> Account_Statement { get; set; }
        public virtual DbSet<Accounting_Balances> Accounting_Balances { get; set; }
        public virtual DbSet<Bills_Profit> Bills_Profit { get; set; }
        public virtual DbSet<Customer_and_Spplier> Customer_and_Spplier { get; set; }
        public virtual DbSet<Customers_Balance> Customers_Balance { get; set; }
        public virtual DbSet<Daily_Stock_Out> Daily_Stock_Out { get; set; }
        public virtual DbSet<inventory> inventory { get; set; }
        public virtual DbSet<Item_Balance> Item_Balance { get; set; }
        public virtual DbSet<Net_Items_Sales_ByDate> Net_Items_Sales_ByDate { get; set; }
        public virtual DbSet<New_Sales_Invoice> New_Sales_Invoice { get; set; }
        public virtual DbSet<Order_History_V> Order_History_V { get; set; }
        public virtual DbSet<ORder_Type> ORder_Type { get; set; }
        public virtual DbSet<Paid_Orders> Paid_Orders { get; set; }
        public virtual DbSet<POS_Bills_Details> POS_Bills_Details { get; set; }
        public virtual DbSet<pos_exp> pos_exp { get; set; }
        public virtual DbSet<POS_Invoice_X> POS_Invoice_X { get; set; }
        public virtual DbSet<POS_REFUND> POS_REFUND { get; set; }
        public virtual DbSet<previous> previous { get; set; }
        public virtual DbSet<Previous_Balance> Previous_Balance { get; set; }
        public virtual DbSet<Print_Deleted_Item> Print_Deleted_Item { get; set; }
        public virtual DbSet<Print_Order> Print_Order { get; set; }
        public virtual DbSet<Print_Shisa> Print_Shisa { get; set; }
        public virtual DbSet<Print_Talbat_Invoice> Print_Talbat_Invoice { get; set; }
        public virtual DbSet<Purchase_Invoice> Purchase_Invoice { get; set; }
        public virtual DbSet<Receipt_and_Payment> Receipt_and_Payment { get; set; }
        public virtual DbSet<Refund> Refund { get; set; }
        public virtual DbSet<Sales_Invoice> Sales_Invoice { get; set; }
        public virtual DbSet<Sales_Bydate> Sales_Bydate { get; set; }
        public virtual DbSet<sales_invoice_XX> sales_invoice_XX { get; set; }
        public virtual DbSet<Sales_Report> Sales_Report { get; set; }
        public virtual DbSet<Sales_report_all> Sales_report_all { get; set; }
        public virtual DbSet<Shieft_Report> Shieft_Report { get; set; }
        public virtual DbSet<Show_Items> Show_Items { get; set; }
        public virtual DbSet<STAFF_SALES> STAFF_SALES { get; set; }
        public virtual DbSet<Subs_Report_New> Subs_Report_New { get; set; }
        public virtual DbSet<Suppliers_Balance> Suppliers_Balance { get; set; }
        public virtual DbSet<View_1> View_1 { get; set; }
        public virtual DbSet<View_5> View_5 { get; set; }
        public virtual DbSet<View_7> View_7 { get; set; }
        public virtual DbSet<View_DAY1> View_DAY1 { get; set; }
        public virtual DbSet<View_DAY2> View_DAY2 { get; set; }
        public virtual DbSet<View_prt_allday> View_prt_allday { get; set; }
        public virtual DbSet<View_shoe_iteme> View_shoe_iteme { get; set; }
        public virtual DbSet<Waiters_Report> Waiters_Report { get; set; }
    }
}
