//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Acc_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accounting_Balances
    {
        public string رقم_الحساب { get; set; }
        public string اسم_الحساب { get; set; }
        public Nullable<double> مجموع_المدين { get; set; }
        public Nullable<double> مجموع_الدائن { get; set; }
        public Nullable<double> الرصيد { get; set; }
        public System.Guid GUID { get; set; }
    }
}
