//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Acc_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account_Statement
    {
        public System.Guid GUID_DAY1 { get; set; }
        public Nullable<int> NUMBER_DAY1 { get; set; }
        public Nullable<System.DateTime> DATE_DAY1 { get; set; }
        public string NOTE_DAY1 { get; set; }
        public Nullable<System.Guid> TYPE_DAY1 { get; set; }
        public string NOTE_DAY1_TYPE { get; set; }
        public Nullable<System.Guid> GUID_JOB_DAY1 { get; set; }
        public string NAME_JOBE_DAY1 { get; set; }
        public Nullable<System.Guid> GUID_CURRENCY_DAY1 { get; set; }
        public string NAME_CURRENCY_DAY1 { get; set; }
        public Nullable<double> CURRENCY_VAL_DAY1 { get; set; }
        public Nullable<System.Guid> PAENT_GUID_DAY2 { get; set; }
        public Nullable<System.Guid> ACCOUNT_GUID_DAY2 { get; set; }
        public string Name_DAY2 { get; set; }
        public Nullable<double> DEBIT_DAY2 { get; set; }
        public Nullable<double> CREDIT_DAY2 { get; set; }
        public string NOTE_DAY2 { get; set; }
        public System.Guid GUID_DAY2 { get; set; }
        public Nullable<System.Guid> GUID_JOB_DAY2 { get; set; }
        public string NAME_JOB_DAY2 { get; set; }
        public Nullable<System.Guid> GUID_CURRENCY_DAY2 { get; set; }
        public string NAME_CURRENCY_DAY2 { get; set; }
        public Nullable<double> CURRENCY_VAL { get; set; }
        public string Reference { get; set; }
    }
}
