//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Acc_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> AppDate { get; set; }
        public string ContactName { get; set; }
        public string Address { get; set; }
        public string Comment { get; set; }
        public string Staff { get; set; }
        public Nullable<System.TimeSpan> from_time { get; set; }
        public Nullable<System.TimeSpan> to_time { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Bill_Ref { get; set; }
    }
}
