//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Acc_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class b1
    {
        public int ID { get; set; }
        public System.Guid GUID { get; set; }
        public Nullable<System.Guid> PARENT_GUID { get; set; }
        public Nullable<int> NUMBER { get; set; }
        public Nullable<System.Guid> CUST { get; set; }
        public string NOTE { get; set; }
        public Nullable<System.Guid> STORE_GUID { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public Nullable<double> disc { get; set; }
        public Nullable<double> EXTEA { get; set; }
        public Nullable<double> p_disc { get; set; }
        public Nullable<double> p_extra { get; set; }
        public Nullable<double> total { get; set; }
        public Nullable<double> type_dis { get; set; }
        public Nullable<double> disc_rate { get; set; }
        public string type_pay { get; set; }
        public Nullable<System.Guid> GUID_JOB { get; set; }
        public Nullable<System.Guid> GUID_CURRENCY { get; set; }
        public Nullable<double> CURRENCY_VAL { get; set; }
        public Nullable<int> DELETE_NUM { get; set; }
        public Nullable<System.DateTime> Date_Delete { get; set; }
        public Nullable<System.Guid> guid_user { get; set; }
        public string CUSTOMER_NAME { get; set; }
        public string CUSTOMER_MOBILE1 { get; set; }
        public string CUSTOMER_MOBILE2 { get; set; }
        public string CUSTOMER_COMPANY { get; set; }
        public string CUSTOMER_STREET { get; set; }
        public string CUSTOMER_PHON { get; set; }
        public string CUSTOMER_EMAIL { get; set; }
        public Nullable<double> PAY_1_PAY { get; set; }
        public Nullable<System.Guid> PAY_1_GUID { get; set; }
        public Nullable<System.Guid> TRAN_POS_GUID { get; set; }
        public Nullable<double> TRAN_POS_PAY { get; set; }
        public Nullable<System.Guid> employee_pos { get; set; }
        public Nullable<System.DateTime> time_bill { get; set; }
    }
}
