//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Acc_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class b2
    {
        public int id { get; set; }
        public System.Guid GUID { get; set; }
        public Nullable<System.Guid> PARENT_GUID { get; set; }
        public Nullable<System.Guid> GUID_ITEME { get; set; }
        public Nullable<double> QTY { get; set; }
        public Nullable<double> PRICE { get; set; }
        public string NOTE { get; set; }
        public Nullable<double> disc { get; set; }
        public Nullable<double> extra { get; set; }
        public Nullable<System.Guid> guid_store { get; set; }
        public string unit { get; set; }
        public Nullable<double> qty_unit { get; set; }
        public Nullable<int> recpt { get; set; }
        public string barcode { get; set; }
        public Nullable<int> order_n { get; set; }
        public Nullable<double> order_qty { get; set; }
        public Nullable<int> item_id { get; set; }
    }
}
