//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Acc_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bills_Profit
    {
        public Nullable<int> NUMBER { get; set; }
        public string NOTE { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public Nullable<double> disc { get; set; }
        public Nullable<double> disc_rate { get; set; }
        public Nullable<System.Guid> guid_user { get; set; }
        public Nullable<System.DateTime> time_bill { get; set; }
        public Nullable<double> Cash { get; set; }
        public Nullable<double> KNET { get; set; }
        public string delivery_customer { get; set; }
        public string delivery_mobile { get; set; }
        public string Sales_Man { get; set; }
        public Nullable<double> Total_Cost { get; set; }
        public Nullable<double> Total { get; set; }
        public Nullable<double> Net_Profit { get; set; }
        public System.Guid GUID { get; set; }
    }
}
