//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Acc_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking_Details
    {
        public int id { get; set; }
        public Nullable<double> QTY { get; set; }
        public Nullable<double> PRICE { get; set; }
        public string NOTE { get; set; }
        public string barcode { get; set; }
        public string Sales_Man { get; set; }
        public Nullable<int> Booking_id { get; set; }
    }
}
