//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Acc_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAR_CARD
    {
        public int ID { get; set; }
        public Nullable<int> NUMBER { get; set; }
        public string OWNER { get; set; }
        public string CIVIL_ID { get; set; }
        public string ADDRESS { get; set; }
        public string PLATE_NO { get; set; }
        public string TYPE_CAR { get; set; }
        public string ENGINE_NO { get; set; }
        public string CONDITION { get; set; }
        public string CHASSIS_NO { get; set; }
        public string MAN_YEAR { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public string BRAND { get; set; }
        public string COUNTRY { get; set; }
        public string COLOR { get; set; }
        public string SHAPE { get; set; }
        public string MOBILE { get; set; }
    }
}
