//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Acc_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CASH_DAY
    {
        public int ID { get; set; }
        public System.Guid GUID { get; set; }
        public Nullable<int> NUMBER { get; set; }
        public Nullable<System.Guid> GUID_ACCOUNT { get; set; }
        public string NOTE { get; set; }
        public Nullable<System.Guid> PARENT_GUID { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public Nullable<System.Guid> GUID_JOB { get; set; }
        public Nullable<System.Guid> GUID_CURRENCY { get; set; }
        public Nullable<double> CURRENCY_VAL { get; set; }
        public Nullable<System.Guid> guid_user { get; set; }
        public string number_document { get; set; }
        public string name_recip { get; set; }
        public string mobile_recipt { get; set; }
        public Nullable<int> ISPOSTED { get; set; }
        public Nullable<int> DELETE_NUM { get; set; }
        public Nullable<System.DateTime> Date_Delete { get; set; }
        public string Customer_name { get; set; }
        public Nullable<double> amount { get; set; }
        public string check_no { get; set; }
        public string Bank { get; set; }
    }
}
