//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Acc_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Config
    {
        public int id { get; set; }
        public Nullable<int> Double_Count { get; set; }
        public string Mail { get; set; }
        public Nullable<int> Send_Mail { get; set; }
        public string Shop_Name { get; set; }
        public Nullable<int> Print_Order { get; set; }
        public Nullable<int> Show_Item_balance { get; set; }
        public Nullable<int> mail2 { get; set; }
        public string mail2_desc { get; set; }
        public Nullable<int> Auto_Print { get; set; }
        public Nullable<int> Show_Sales_man { get; set; }
        public Nullable<int> Sum_Qty { get; set; }
        public Nullable<int> icon_H { get; set; }
        public Nullable<int> icon_V { get; set; }
        public string Panel9_Size { get; set; }
        public string Sender_Mail { get; set; }
        public string Mail_Pass { get; set; }
        public string font_size { get; set; }
        public byte[] Company_Logo { get; set; }
        public Nullable<int> icon2_h { get; set; }
        public Nullable<int> icon2_v { get; set; }
        public string Printer { get; set; }
        public Nullable<int> Button_Images { get; set; }
        public Nullable<int> Purchase_Expenses { get; set; }
        public Nullable<int> Print_KOT_First { get; set; }
        public string Over_Sale { get; set; }
        public string Restaurant_tools { get; set; }
        public string Order_Delete { get; set; }
        public string Show_printed_Bill { get; set; }
        public string Show_Login { get; set; }
        public string Category_Panel_High { get; set; }
        public Nullable<int> break_select_customer { get; set; }
        public Nullable<int> POS_Change_Price { get; set; }
        public Nullable<int> Order_System { get; set; }
        public Nullable<int> TABLE_SECURITY { get; set; }
        public Nullable<int> order_type { get; set; }
        public Nullable<int> pos_show_img { get; set; }
        public Nullable<int> is_Restaurant { get; set; }
        public Nullable<int> Tablet_Mode { get; set; }
        public Nullable<int> Query_Img { get; set; }
        public byte[] default_image { get; set; }
        public Nullable<int> scall_Barcode_start { get; set; }
        public Nullable<int> scall_Barcode_length { get; set; }
        public Nullable<int> scall_Price_start { get; set; }
        public Nullable<int> scall_Price_length { get; set; }
        public string Kichen_Printer { get; set; }
        public string Multi_Prices { get; set; }
        public string Print_Invoice_Proccess { get; set; }
        public string Talbat_Extra { get; set; }
        public string Category_Color { get; set; }
        public string Items_Color { get; set; }
        public string Bar_Printer { get; set; }
        public string Shisha_Printer { get; set; }
        public string PrintOtherReport { get; set; }
        public string Invoice_Split { get; set; }
        public string Round { get; set; }
        public string DefaultItem { get; set; }
        public string Update_Recipes { get; set; }
        public string DininTabletMode { get; set; }
        public string ARandENLabel { get; set; }
        public string LoadOrderTypes { get; set; }
        public string thTopHeader { get; set; }
        public string thTopHeaderFonts { get; set; }
        public string thTopHeaderFontsSize { get; set; }
        public string thTopHeaderPanelHeight { get; set; }
        public string thMainPanelColor { get; set; }
        public string thMainButtonColor { get; set; }
        public string thHighlighButtonColor { get; set; }
        public string thMainButtonColorFont { get; set; }
        public string thHighlighButtonColorFont { get; set; }
        public string thMainPanelFontColor { get; set; }
        public string thMiddlePanelColor { get; set; }
        public string Kichendoubleprint { get; set; }
    }
}
