//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Acc_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contract
    {
        public int id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Customer { get; set; }
        public string Building { get; set; }
        public string Area { get; set; }
        public string Block { get; set; }
        public string Street { get; set; }
        public string Jaddah { get; set; }
        public string Tele { get; set; }
        public string Car_No { get; set; }
        public string Car_Type { get; set; }
        public string Point1 { get; set; }
        public string Point2 { get; set; }
        public string Point3 { get; set; }
        public string Point4 { get; set; }
        public string Point5 { get; set; }
        public Nullable<double> amount { get; set; }
        public Nullable<double> pay1 { get; set; }
        public Nullable<double> pay2 { get; set; }
        public Nullable<double> pay3 { get; set; }
        public Nullable<double> pay4 { get; set; }
        public Nullable<System.DateTime> date1 { get; set; }
        public Nullable<System.DateTime> date2 { get; set; }
        public Nullable<System.DateTime> date3 { get; set; }
        public Nullable<System.DateTime> date4 { get; set; }
        public string duration { get; set; }
        public Nullable<System.DateTime> start { get; set; }
    }
}
