//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Acc_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CURRENCY
    {
        public int id { get; set; }
        public string NAME { get; set; }
        public string PART_NAME { get; set; }
        public Nullable<double> CURRENCY_VAL { get; set; }
        public System.Guid GUID { get; set; }
        public Nullable<System.Guid> guid_user { get; set; }
    }
}
