//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Acc_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_and_Spplier
    {
        public System.Guid GUID { get; set; }
        public string Name { get; set; }
        public Nullable<System.Guid> ParentGUID { get; set; }
        public string Code { get; set; }
        public Nullable<int> END_ACCOUNT { get; set; }
    }
}
