//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Acc_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DAY1
    {
        public int id { get; set; }
        public Nullable<int> NUMBER_D { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public string NOTE { get; set; }
        public Nullable<System.Guid> TYPE { get; set; }
        public string note_day { get; set; }
        public Nullable<System.Guid> GUID_JOB { get; set; }
        public Nullable<System.Guid> GUID_CURRENCY { get; set; }
        public Nullable<double> CURRENCY_VAL { get; set; }
        public Nullable<int> Date_Delete { get; set; }
        public Nullable<System.Guid> guid_user { get; set; }
        public System.Guid GUID { get; set; }
        public string Reference { get; set; }
    }
}
