//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Acc_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DAY2
    {
        public int id { get; set; }
        public Nullable<System.Guid> PAENT_GUID { get; set; }
        public Nullable<System.Guid> ACCOUNT_GUID { get; set; }
        public Nullable<double> DEBIT { get; set; }
        public Nullable<double> CREDIT { get; set; }
        public string NOTE { get; set; }
        public System.Guid GUID { get; set; }
        public Nullable<System.Guid> GUID_JOB { get; set; }
        public Nullable<System.Guid> GUID_CURRENCY { get; set; }
        public Nullable<double> CURRENCY_VAL { get; set; }
    }
}
