//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Acc_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dayee
    {
        public int id { get; set; }
        public string num { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<System.DateTime> timee { get; set; }
        public Nullable<System.Guid> guid_user { get; set; }
        public string action { get; set; }
        public Nullable<System.Guid> guid_type { get; set; }
        public string not_type { get; set; }
    }
}
