//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Acc_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DELIVERY_CUSTOMERS
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public Nullable<int> MOBLIE { get; set; }
        public string GOVERNMENT { get; set; }
        public string CITY { get; set; }
        public string BLOCK { get; set; }
        public string STREET { get; set; }
        public string BUILDING { get; set; }
        public string FLOOR { get; set; }
        public string ROOM { get; set; }
        public string NOTES { get; set; }
        public Nullable<int> Subs_ID { get; set; }
        public string Status { get; set; }
        public Nullable<int> Discount { get; set; }
        public string Driver { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
