//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Acc_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE
    {
        public int ID { get; set; }
        public Nullable<System.Guid> GUID { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<System.DateTime> DTP { get; set; }
        public string NAME { get; set; }
        public string LASTNAME { get; set; }
        public string COMPANY { get; set; }
        public string COMPANYJOB { get; set; }
        public string CUNTRY { get; set; }
        public string STREET { get; set; }
        public string PHON { get; set; }
        public string MOB1 { get; set; }
        public string MOB2 { get; set; }
        public string MAIL { get; set; }
        public string WEB { get; set; }
        public byte[] img { get; set; }
        public string Nationality { get; set; }
        public string idinsurance { get; set; }
        public Nullable<System.DateTime> bgndate { get; set; }
        public Nullable<System.DateTime> enddate { get; set; }
        public Nullable<System.DateTime> inp { get; set; }
        public Nullable<System.DateTime> outpu { get; set; }
        public Nullable<double> salary { get; set; }
        public Nullable<double> taxes { get; set; }
        public Nullable<double> insurance { get; set; }
        public string statuse { get; set; }
        public string CARD { get; set; }
        public string TXTNationality { get; set; }
        public Nullable<int> idjob { get; set; }
        public string father { get; set; }
        public string mather { get; set; }
        public string bloodtype { get; set; }
        public string CountryBirths { get; set; }
        public string RegistrationNo { get; set; }
        public string Box { get; set; }
        public string IDnumber { get; set; }
        public Nullable<System.DateTime> date_IDnumber { get; set; }
        public string Army { get; set; }
        public Nullable<System.DateTime> date_b_Army { get; set; }
        public Nullable<System.DateTime> date_e_Army { get; set; }
        public string country_Army { get; set; }
        public string Family_status { get; set; }
        public string number_wives { get; set; }
        public string Number_Children { get; set; }
        public string Insurance_facility { get; set; }
        public string ID_Insurance_facility { get; set; }
        public Nullable<System.DateTime> DATE_B_Insurance_facility { get; set; }
        public Nullable<System.DateTime> DATE_E_Insurance_facility { get; set; }
        public Nullable<System.Guid> GUID_ACCOUNT { get; set; }
        public Nullable<System.Guid> guid_user { get; set; }
    }
}
