//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Acc_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE_LEARN
    {
        public int ID { get; set; }
        public Nullable<int> ID_STUDENT { get; set; }
        public Nullable<int> ID_LEARNING { get; set; }
        public Nullable<System.DateTime> DATE_B { get; set; }
        public Nullable<System.DateTime> DATE_E { get; set; }
        public string t_EMPLOYEE_LEARN { get; set; }
        public string coun_EMPLOYEE_LEARN { get; set; }
    }
}
