//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Acc_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_Emp_Card
    {
        public int ID { get; set; }
        public Nullable<int> Emp_Code { get; set; }
        public string Emp_Name { get; set; }
        public string Emp_En_Name { get; set; }
        public string Education { get; set; }
        public string Sex { get; set; }
        public Nullable<System.DateTime> Birth_Date { get; set; }
        public string Regional { get; set; }
        public string Company_Job { get; set; }
        public byte[] Emp_Pic { get; set; }
        public string Gov_Emp_no { get; set; }
        public Nullable<double> Gov_Salary { get; set; }
        public string Gov_Permit_NO { get; set; }
        public string Gov_Work_Place { get; set; }
        public Nullable<System.DateTime> Gov_Hire_Date { get; set; }
        public Nullable<System.DateTime> Gover_Work_Received { get; set; }
        public Nullable<System.DateTime> Gov_Permit_Start { get; set; }
        public Nullable<System.DateTime> Gov_Permit_End { get; set; }
        public string Health_no { get; set; }
        public Nullable<System.DateTime> Health_Start { get; set; }
        public Nullable<System.DateTime> Health_ENd { get; set; }
        public Nullable<System.DateTime> D_License_Start { get; set; }
        public Nullable<System.DateTime> D_License_End { get; set; }
        public string Pass_No { get; set; }
        public string C_ID { get; set; }
        public string Pass_Type { get; set; }
        public Nullable<System.DateTime> Enter_DAte { get; set; }
        public Nullable<System.DateTime> Pass_Start_Date { get; set; }
        public Nullable<System.DateTime> Pass_End_Date { get; set; }
        public string PAss_Conntry { get; set; }
        public string Pass_NAtionality { get; set; }
        public string Activity { get; set; }
        public string Eqqama_No { get; set; }
        public string Eqqama_Type { get; set; }
        public string Owner_ { get; set; }
        public string Company { get; set; }
        public string Registeration { get; set; }
        public Nullable<System.DateTime> Eqqama_Start { get; set; }
        public Nullable<System.DateTime> Eqqama_End { get; set; }
    }
}
