//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Acc_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventory
    {
        public string BARCODE_1 { get; set; }
        public string NAME { get; set; }
        public Nullable<double> Expr1 { get; set; }
        public System.Guid GUID { get; set; }
        public string Store { get; set; }
        public string Group_Name { get; set; }
        public string TYPE_ITEME { get; set; }
        public Nullable<double> AVG_PRICE { get; set; }
        public Nullable<double> EndUser { get; set; }
        public string UNIT2 { get; set; }
        public Nullable<double> QTY_UNIT2 { get; set; }
        public Nullable<double> Qty2 { get; set; }
        public string latin_name { get; set; }
        public string Company { get; set; }
        public Nullable<double> MIN_QTY { get; set; }
    }
}
