//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Acc_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class iteme
    {
        public int ID { get; set; }
        public Nullable<System.Guid> GUID { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public string NAME { get; set; }
        public string NOTE { get; set; }
        public string GROUP_GUID { get; set; }
        public Nullable<double> BALANCE { get; set; }
        public Nullable<double> AVG_PRICE { get; set; }
        public string UNIT1 { get; set; }
        public Nullable<double> QTY_UNIT1 { get; set; }
        public string BARCODE_1 { get; set; }
        public string UNIT2 { get; set; }
        public Nullable<double> QTY_UNIT2 { get; set; }
        public string BARCODE_2 { get; set; }
        public string UNIT3 { get; set; }
        public Nullable<double> QTY_UNIT3 { get; set; }
        public string BARCODE_3 { get; set; }
        public string latin_name { get; set; }
        public string Company { get; set; }
        public string Provenance { get; set; }
        public string Quality { get; set; }
        public string Color { get; set; }
        public string Model { get; set; }
        public string Dim { get; set; }
        public string Pos { get; set; }
        public string Origin { get; set; }
        public string guid_user { get; set; }
        public string guid_currency { get; set; }
        public Nullable<double> Whole { get; set; }
        public Nullable<double> Half { get; set; }
        public Nullable<double> EndUser { get; set; }
        public Nullable<double> Vendor { get; set; }
        public Nullable<double> Export { get; set; }
        public Nullable<double> Retail { get; set; }
        public Nullable<double> LastPrice { get; set; }
        public string OrderLimit { get; set; }
        public Nullable<double> MAX_QTY { get; set; }
        public Nullable<double> MIN_QTY { get; set; }
        public string TYPE_ITEME { get; set; }
        public Nullable<double> vat { get; set; }
        public string is_remove { get; set; }
        public string type { get; set; }
        public string Status { get; set; }
        public string Is_Sales { get; set; }
        public byte[] image { get; set; }
        public Nullable<int> Sort { get; set; }
        public string UNIT4 { get; set; }
        public Nullable<double> QTY_UNIT4 { get; set; }
        public string BARCODE_4 { get; set; }
        public string UNIT5 { get; set; }
        public Nullable<double> QTY_UNIT5 { get; set; }
        public string BARCODE_5 { get; set; }
        public string UNIT6 { get; set; }
        public Nullable<double> QTY_UNIT6 { get; set; }
        public string BARCODE_6 { get; set; }
        public Nullable<double> PRICE_4 { get; set; }
        public Nullable<double> PRICE_5 { get; set; }
        public Nullable<double> PRICE_6 { get; set; }
        public byte[] pic_1 { get; set; }
        public byte[] pic_2 { get; set; }
        public byte[] pic_3 { get; set; }
        public byte[] pic_4 { get; set; }
        public byte[] pic_5 { get; set; }
        public byte[] pic_6 { get; set; }
        public Nullable<int> GROUP_ID { get; set; }
        public string Color2 { get; set; }
    }
}
