//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Acc_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Net_Items_Sales_ByDate
    {
        public string NAME { get; set; }
        public Nullable<double> Total_Qty_Refund { get; set; }
        public Nullable<double> Total_Qty_Sold { get; set; }
        public Nullable<double> Purchase { get; set; }
        public Nullable<double> R_Purchase { get; set; }
        public Nullable<double> B_Inventory { get; set; }
        public Nullable<double> NET_Qty { get; set; }
        public Nullable<double> PRICE { get; set; }
        public Nullable<double> Total { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public Nullable<int> shift_no { get; set; }
        public Nullable<double> AVG_PRICE { get; set; }
        public Nullable<double> disc { get; set; }
        public Nullable<double> Item_Net_Price { get; set; }
        public Nullable<double> net_value { get; set; }
        public string Sales_Man { get; set; }
        public string Expr1 { get; set; }
        public string delivery_customer { get; set; }
        public string delivery_mobile { get; set; }
        public Nullable<double> Expr2 { get; set; }
        public string Group_Name { get; set; }
        public Nullable<double> Total_Invoice { get; set; }
        public Nullable<double> disc_rate { get; set; }
        public Nullable<double> Item_Total_Discount { get; set; }
        public Nullable<double> Subs_Paid { get; set; }
        public Nullable<int> NUMBER { get; set; }
        public string car_plate_no { get; set; }
        public Nullable<int> car_current_counter { get; set; }
        public Nullable<System.Guid> PARENT_GUID { get; set; }
        public string NOTE { get; set; }
        public string city { get; set; }
        public string block { get; set; }
        public string street { get; set; }
        public string building { get; set; }
        public string floor { get; set; }
        public string room { get; set; }
        public string add_Details { get; set; }
        public string Driver { get; set; }
        public Nullable<double> BALANCE { get; set; }
        public string unit { get; set; }
        public string TYPE_ITEME { get; set; }
        public Nullable<double> MIN_QTY { get; set; }
        public int id { get; set; }
        public string Printer { get; set; }
        public string latin_name { get; set; }
        public string Branch { get; set; }
        public Nullable<double> qty_unit { get; set; }
        public string BARCODE_1 { get; set; }
        public string TypeBill { get; set; }
        public System.Guid GUID { get; set; }
        public Nullable<System.Guid> Expr3 { get; set; }
        public System.Guid Expr4 { get; set; }
        public System.Guid Expr5 { get; set; }
        public System.Guid Expr6 { get; set; }
        public int Expr7 { get; set; }
        public int Expr8 { get; set; }
        public int Expr9 { get; set; }
        public int Expr10 { get; set; }
    }
}
