//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Acc_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_History_V
    {
        public string NAME { get; set; }
        public Nullable<double> QTY { get; set; }
        public Nullable<double> PRICE { get; set; }
        public string barcode { get; set; }
        public string table_no { get; set; }
        public string Waiter { get; set; }
        public Nullable<System.DateTime> Time_Punch { get; set; }
        public string Category { get; set; }
        public Nullable<double> TOTAL { get; set; }
        public int ID { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string shift { get; set; }
        public string isCanceled { get; set; }
        public string isTransfer { get; set; }
    }
}
