//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Acc_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_types
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public string Commission { get; set; }
        public string DisplayName { get; set; }
        public string Color { get; set; }
        public Nullable<int> Active { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
    }
}
