//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Acc_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order2
    {
        public int ID { get; set; }
        public Nullable<int> Master_ID { get; set; }
        public string Barcode { get; set; }
        public string Item { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> Total_Line { get; set; }
        public string Line_Note { get; set; }
    }
}
