//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Acc_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORder_Type
    {
        public Nullable<System.Guid> PARENT_GUID { get; set; }
        public Nullable<double> Total { get; set; }
        public string NOTE { get; set; }
        public Nullable<double> KNET { get; set; }
        public Nullable<System.DateTime> time_bill { get; set; }
        public Nullable<int> NUMBER { get; set; }
        public int ID { get; set; }
        public Nullable<double> Cash { get; set; }
    }
}
