//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Acc_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paid_Orders
    {
        public Nullable<int> NUMBER { get; set; }
        public Nullable<System.DateTime> time_bill { get; set; }
        public Nullable<int> shift_no { get; set; }
        public string Sales_Man { get; set; }
        public Nullable<double> PRICE { get; set; }
        public Nullable<double> QTY { get; set; }
        public string Category { get; set; }
        public string Item_Name { get; set; }
        public Nullable<System.Guid> PARENT_GUID { get; set; }
        public int ID { get; set; }
    }
}
