//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Acc_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class personal
    {
        public int id { get; set; }
        public Nullable<System.Guid> customer { get; set; }
        public Nullable<System.Guid> vender { get; set; }
        public Nullable<System.Guid> student { get; set; }
        public Nullable<System.Guid> employee { get; set; }
    }
}
