//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Acc_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POS_Shieft
    {
        public int id { get; set; }
        public string user_name { get; set; }
        public Nullable<double> cash { get; set; }
        public Nullable<double> visa { get; set; }
        public Nullable<double> total { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public string status { get; set; }
        public Nullable<double> pos_expenses { get; set; }
        public string salesman { get; set; }
        public Nullable<double> R_total { get; set; }
        public Nullable<double> R_Cash { get; set; }
        public Nullable<double> R_Knet { get; set; }
        public Nullable<double> N_Total { get; set; }
        public Nullable<double> N_Cash { get; set; }
        public Nullable<double> N_KNET { get; set; }
        public Nullable<int> Number { get; set; }
        public Nullable<double> Master { get; set; }
        public Nullable<double> Visa_Card { get; set; }
        public Nullable<double> Open_Orders { get; set; }
        public Nullable<double> Subs { get; set; }
        public Nullable<double> jeebly { get; set; }
        public Nullable<double> deliveroo { get; set; }
        public Nullable<double> Open_Balance { get; set; }
        public Nullable<double> Talbat_Cash { get; set; }
        public Nullable<double> Talbat_Knet { get; set; }
        public Nullable<double> Deliveroo_Cash { get; set; }
        public Nullable<double> Deliveroo_Knet { get; set; }
        public Nullable<double> TAKEAWAY_CASH { get; set; }
        public Nullable<double> TAKEAWAY_KNET { get; set; }
        public Nullable<double> DELIVERY_CASH { get; set; }
        public Nullable<double> DELIVERY_KNET { get; set; }
        public string branch { get; set; }
        public Nullable<System.Guid> Guid { get; set; }
        public string Stock_Trans { get; set; }
        public Nullable<double> DininCash { get; set; }
        public Nullable<double> DininKNET { get; set; }
        public Nullable<double> ManasatiCash { get; set; }
        public Nullable<double> ManasatiKNET { get; set; }
    }
}
