//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Acc_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POS_USERS
    {
        public int id { get; set; }
        public string USER_NAME { get; set; }
        public Nullable<int> USER_PIN { get; set; }
        public string USER_TYPE { get; set; }
        public Nullable<int> STATUS { get; set; }
        public string Language { get; set; }
        public string Branch { get; set; }
        public string MaxDiscount { get; set; }
        public Nullable<int> AccessRefund { get; set; }
        public Nullable<int> OpenCachDrawer { get; set; }
        public Nullable<int> TransferTable { get; set; }
        public Nullable<int> SplitInvoice { get; set; }
        public Nullable<int> DeleteOrder { get; set; }
        public Nullable<int> RePrintReceipt { get; set; }
    }
}
