//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Acc_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pos_money_receipt
    {
        public int id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string customer { get; set; }
        public string mobile { get; set; }
        public Nullable<double> balance { get; set; }
        public Nullable<double> paid_cash { get; set; }
        public Nullable<double> paid_knet { get; set; }
        public Nullable<double> remain { get; set; }
    }
}
