//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Acc_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POS_Expenses
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.Guid> user_ { get; set; }
        public Nullable<double> Value { get; set; }
        public string notes { get; set; }
        public string status { get; set; }
        public Nullable<int> shieft_no { get; set; }
        public string salesman { get; set; }
        public string Category { get; set; }
        public Nullable<System.Guid> Guid { get; set; }
    }
}
