//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Acc_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POS_REFUND
    {
        public Nullable<int> invoice_no { get; set; }
        public string header_notes { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public Nullable<double> invoice_discount { get; set; }
        public Nullable<double> total { get; set; }
        public Nullable<double> disc_rate { get; set; }
        public Nullable<double> type_dis { get; set; }
        public string user_name { get; set; }
        public int user_id { get; set; }
        public Nullable<System.DateTime> time_bill { get; set; }
        public Nullable<double> Cash { get; set; }
        public Nullable<double> KNET { get; set; }
        public string delivery_customer { get; set; }
        public string delivery_mobile { get; set; }
        public string Govern { get; set; }
        public string city { get; set; }
        public string block { get; set; }
        public string street { get; set; }
        public string building { get; set; }
        public string floor { get; set; }
        public string room { get; set; }
        public string add_Details { get; set; }
        public Nullable<double> Reset { get; set; }
        public string Driver { get; set; }
        public string Driver_tele { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<double> QTY { get; set; }
        public Nullable<double> PRICE { get; set; }
        public string Expr2 { get; set; }
        public Nullable<double> Expr4 { get; set; }
        public string barcode { get; set; }
        public Nullable<int> item_id { get; set; }
        public string item_name { get; set; }
        public int Expr6 { get; set; }
        public string Expr7 { get; set; }
        public string Expr1 { get; set; }
        public string Sales_Man { get; set; }
        public Nullable<double> VAT { get; set; }
        public string table_no { get; set; }
        public Nullable<int> SN { get; set; }
        public string ORDER_TYPE { get; set; }
        public System.Guid GUID { get; set; }
        public Nullable<double> Subs_Paid { get; set; }
        public string Subs_Balance { get; set; }
        public Nullable<System.DateTime> Subs_End_Date { get; set; }
        public Nullable<System.DateTime> Booking_Date { get; set; }
        public Nullable<System.DateTime> Booking_Time { get; set; }
        public string Expr8 { get; set; }
        public Nullable<double> VISA { get; set; }
        public Nullable<double> MASTER { get; set; }
        public string unit { get; set; }
        public string latin_name { get; set; }
        public Nullable<double> TRAN_POS_PAY { get; set; }
        public Nullable<int> CUSTOMER_MOBILE1 { get; set; }
        public Nullable<int> shift_no { get; set; }
        public string Gategory { get; set; }
        public string CUSTOMER_PHON { get; set; }
        public Nullable<double> CUSTOMER_STREET { get; set; }
        public string CUSTOMER_EMAIL { get; set; }
        public Nullable<double> CUSTOMER_COMPANY { get; set; }
        public string CUSTOMER_MOBILE2 { get; set; }
        public string Expr3 { get; set; }
    }
}
