//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Acc_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POS_Bills_Details
    {
        public string NAME { get; set; }
        public Nullable<int> NUMBER { get; set; }
        public string NOTE { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public Nullable<System.DateTime> time_bill { get; set; }
        public Nullable<double> p_disc { get; set; }
        public Nullable<double> disc { get; set; }
        public Nullable<double> EXTEA { get; set; }
        public Nullable<double> Total { get; set; }
        public Nullable<double> Cash { get; set; }
        public Nullable<double> KNET { get; set; }
        public Nullable<double> VISA { get; set; }
        public Nullable<double> MASTER { get; set; }
        public string delivery_customer { get; set; }
        public string delivery_mobile { get; set; }
        public Nullable<int> shift_no { get; set; }
        public string table_no { get; set; }
        public string Branch { get; set; }
        public System.Guid GUID { get; set; }
        public System.Guid Expr1 { get; set; }
        public int ID { get; set; }
        public string Park { get; set; }
    }
}
