//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Acc_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POS_CUSTOMERS_GROUP
    {
        public int ID { get; set; }
        public string GRIUP_NAME { get; set; }
        public Nullable<double> G_DISCOUNT { get; set; }
    }
}
