//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Acc_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POS_CUSTOMERS
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public string MOBILE { get; set; }
        public string EMAIL { get; set; }
        public string NOTES { get; set; }
        public string CITY { get; set; }
        public string BLOCK { get; set; }
        public string STREET { get; set; }
        public string BUIDLING { get; set; }
        public string FLOOR { get; set; }
        public string ROOM { get; set; }
        public string GROUP_NAME { get; set; }
        public Nullable<double> CUSTOMER_DISCOUNT { get; set; }
        public string STATUS { get; set; }
        public string ADDRESS_DETAILS { get; set; }
    }
}
