//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Acc_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pos_exp
    {
        public int الرقم { get; set; }
        public string التاريخ { get; set; }
        public Nullable<double> القيمة { get; set; }
        public string ملاحظات { get; set; }
        public Nullable<int> رقم_الوردية { get; set; }
        public string البائع { get; set; }
    }
}
