//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Acc_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Print_Shisa
    {
        public Nullable<int> Invoice_No { get; set; }
        public string Header_Notes { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public Nullable<double> Invoice_Discount { get; set; }
        public Nullable<double> Total_Invoice { get; set; }
        public Nullable<double> disc_rate { get; set; }
        public Nullable<double> type_dis { get; set; }
        public string User_Name { get; set; }
        public int User_ID { get; set; }
        public Nullable<System.DateTime> time_bill { get; set; }
        public Nullable<double> Cash { get; set; }
        public Nullable<double> KNET { get; set; }
        public string delivery_customer { get; set; }
        public string delivery_mobile { get; set; }
        public string Govern { get; set; }
        public string city { get; set; }
        public string block { get; set; }
        public string street { get; set; }
        public string building { get; set; }
        public string floor { get; set; }
        public string room { get; set; }
        public string add_Details { get; set; }
        public Nullable<double> Reset { get; set; }
        public string Driver { get; set; }
        public string Driver_tele { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<double> QTY { get; set; }
        public Nullable<double> PRICE { get; set; }
        public string NOTE { get; set; }
        public Nullable<double> disc { get; set; }
        public string barcode { get; set; }
        public Nullable<int> item_id { get; set; }
        public string NAME { get; set; }
        public int ID { get; set; }
        public string Item_Note { get; set; }
        public string Expr1 { get; set; }
        public string Sales_Man { get; set; }
        public Nullable<double> VAT { get; set; }
        public string table_no { get; set; }
        public Nullable<int> SN { get; set; }
        public string ORDER_TYPE { get; set; }
        public System.Guid GUID { get; set; }
        public Nullable<double> Subs_Paid { get; set; }
        public string Subs_Balance { get; set; }
        public Nullable<System.DateTime> Subs_End_Date { get; set; }
        public Nullable<System.DateTime> Booking_Date { get; set; }
        public Nullable<System.DateTime> Booking_Time { get; set; }
        public string Expr2 { get; set; }
        public Nullable<double> VISA { get; set; }
        public Nullable<double> MASTER { get; set; }
        public string unit { get; set; }
        public string latin_name { get; set; }
        public Nullable<double> TRAN_POS_PAY { get; set; }
        public string Gategory { get; set; }
        public System.Guid Expr3 { get; set; }
    }
}
