//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Acc_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Print_Talbat_Invoice
    {
        public int bill_id { get; set; }
        public System.Guid Bill_Guid { get; set; }
        public Nullable<System.Guid> PARENT_GUID { get; set; }
        public Nullable<int> NUMBER { get; set; }
        public Nullable<System.Guid> CUST { get; set; }
        public Nullable<System.Guid> STORE_GUID { get; set; }
        public string NOTE { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public Nullable<double> disc { get; set; }
        public Nullable<double> EXTEA { get; set; }
        public Nullable<double> p_disc { get; set; }
        public Nullable<double> p_extra { get; set; }
        public Nullable<double> Total { get; set; }
        public Nullable<double> type_dis { get; set; }
        public Nullable<double> disc_rate { get; set; }
        public string type_pay { get; set; }
        public Nullable<System.Guid> GUID_JOB { get; set; }
        public Nullable<System.Guid> GUID_CURRENCY { get; set; }
        public Nullable<double> CURRENCY_VAL { get; set; }
        public Nullable<int> DELETE_NUM { get; set; }
        public Nullable<System.DateTime> Date_Delete { get; set; }
        public Nullable<System.Guid> guid_user { get; set; }
        public string CUSTOMER_NAME { get; set; }
        public string CUSTOMER_MOBILE1 { get; set; }
        public string CUSTOMER_MOBILE2 { get; set; }
        public string CUSTOMER_COMPANY { get; set; }
        public string CUSTOMER_STREET { get; set; }
        public string CUSTOMER_PHON { get; set; }
        public string CUSTOMER_EMAIL { get; set; }
        public Nullable<double> PAY_1_PAY { get; set; }
        public Nullable<System.Guid> PAY_1_GUID { get; set; }
        public Nullable<System.Guid> TRAN_POS_GUID { get; set; }
        public Nullable<double> TRAN_POS_PAY { get; set; }
        public Nullable<System.Guid> employee_pos { get; set; }
        public Nullable<System.DateTime> time_bill { get; set; }
        public Nullable<double> VAT { get; set; }
        public Nullable<double> Cash { get; set; }
        public Nullable<double> KNET { get; set; }
        public string delivery_customer { get; set; }
        public string delivery_mobile { get; set; }
        public string Govern { get; set; }
        public string city { get; set; }
        public string block { get; set; }
        public string street { get; set; }
        public string building { get; set; }
        public string floor { get; set; }
        public string room { get; set; }
        public string add_Details { get; set; }
        public Nullable<double> Reset { get; set; }
        public string Driver { get; set; }
        public string Driver_tele { get; set; }
        public Nullable<bool> Status { get; set; }
        public string name { get; set; }
        public Nullable<double> QTY { get; set; }
        public Nullable<double> PRICE { get; set; }
        public string Note2 { get; set; }
        public Nullable<double> Dis__ { get; set; }
        public Nullable<double> extra { get; set; }
        public Nullable<System.Guid> guid_store { get; set; }
        public string unit { get; set; }
        public Nullable<double> qty_unit { get; set; }
        public Nullable<int> recpt { get; set; }
        public string barcode { get; set; }
        public Nullable<double> order_qty { get; set; }
        public Nullable<int> order_n { get; set; }
        public Nullable<double> Vat__ { get; set; }
        public Nullable<int> item_id { get; set; }
        public System.Guid GUID { get; set; }
        public int id { get; set; }
        public int Item_id2 { get; set; }
        public string Item_NAme { get; set; }
        public string Item_note { get; set; }
        public Nullable<double> BALANCE { get; set; }
        public Nullable<double> AVG_PRICE { get; set; }
        public string UNIT1 { get; set; }
        public Nullable<double> QTY_UNIT1 { get; set; }
        public Nullable<double> BARCODE_1 { get; set; }
        public Nullable<System.DateTime> UNIT2 { get; set; }
        public Nullable<double> QTY_UNIT2 { get; set; }
        public string BARCODE_2 { get; set; }
        public string UNIT3 { get; set; }
        public Nullable<double> QTY_UNIT3 { get; set; }
        public string BARCODE_3 { get; set; }
        public string latin_name { get; set; }
        public string Company { get; set; }
        public string Provenance { get; set; }
        public string Quality { get; set; }
        public string Color { get; set; }
        public string Model { get; set; }
        public string Dim { get; set; }
        public string Pos { get; set; }
        public string Origin { get; set; }
        public string User_Guid { get; set; }
        public string Currency_Guid { get; set; }
        public Nullable<double> Whole { get; set; }
        public Nullable<double> Half { get; set; }
        public Nullable<double> Vendor { get; set; }
        public Nullable<double> EndUser { get; set; }
        public Nullable<double> Export { get; set; }
        public Nullable<double> Retail { get; set; }
        public Nullable<double> LastPrice { get; set; }
        public Nullable<double> OrderLimit { get; set; }
        public Nullable<double> MAX_QTY { get; set; }
        public Nullable<double> MIN_QTY { get; set; }
        public Nullable<double> Vat_ { get; set; }
        public Nullable<double> TYPE_ITEME { get; set; }
    }
}
