//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Acc_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Print_Item
    {
        public int id { get; set; }
        public string item { get; set; }
        public string emp { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> Invoice_No { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
