//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Acc_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Print_Deleted_Item
    {
        public string Barcode { get; set; }
        public string item { get; set; }
        public Nullable<System.DateTime> time { get; set; }
        public string Table_no { get; set; }
        public Nullable<int> Shieft_ID { get; set; }
        public string user_ { get; set; }
        public string Printer { get; set; }
        public int id { get; set; }
        public string Qty { get; set; }
    }
}
