//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Acc_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROMO_CODE
    {
        public int ID { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<System.DateTime> EXPIRY_DATE { get; set; }
        public Nullable<double> DISCOUNT { get; set; }
        public Nullable<int> STATUS { get; set; }
        public string CODE { get; set; }
    }
}
