//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Acc_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receipt_Design
    {
        public int ID { get; set; }
        public string Compnay_Name { get; set; }
        public string Adress { get; set; }
        public string Mobile { get; set; }
        public string Instagram { get; set; }
        public string Snapchat { get; set; }
        public byte[] Logo { get; set; }
        public string Invoice_Footer { get; set; }
    }
}
