//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Acc_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receipt_and_Payment
    {
        public Nullable<int> NUMBER_D { get; set; }
        public Nullable<double> CREDIT { get; set; }
        public Nullable<double> DEBIT { get; set; }
        public string Name { get; set; }
        public Nullable<System.Guid> TYPE { get; set; }
        public Nullable<int> NUMBER { get; set; }
        public string NOTE { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public string name_recip { get; set; }
        public string mobile_recipt { get; set; }
        public string Type_name { get; set; }
        public System.Guid GUID { get; set; }
        public string number_document { get; set; }
        public string Line_Note { get; set; }
        public string Customer_name { get; set; }
        public Nullable<double> amount { get; set; }
        public string check_no { get; set; }
        public string Bank { get; set; }
        public Nullable<int> CODE { get; set; }
    }
}
