//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Acc_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RELATED_ITEMS
    {
        public int ID { get; set; }
        public string PARENT_BARCODE { get; set; }
        public string PARENT_NAME { get; set; }
        public string BARCODE { get; set; }
        public string PRODUCT { get; set; }
    }
}
