//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Acc_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales_report_all
    {
        public Nullable<int> NUMBER { get; set; }
        public Nullable<double> total { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public Nullable<System.DateTime> time_bill { get; set; }
        public Nullable<double> cash { get; set; }
        public Nullable<double> knet { get; set; }
        public string delivery_customer { get; set; }
        public string delivery_mobile { get; set; }
        public Nullable<double> Reset { get; set; }
        public string Govern { get; set; }
        public string city { get; set; }
        public string block { get; set; }
        public string street { get; set; }
        public string building { get; set; }
        public string floor { get; set; }
        public string room { get; set; }
        public string add_Details { get; set; }
        public string Driver { get; set; }
        public string Driver_tele { get; set; }
        public Nullable<double> VAT { get; set; }
        public Nullable<System.Guid> guid_user { get; set; }
        public Nullable<double> CURRENCY_VAL { get; set; }
        public Nullable<System.Guid> GUID_CURRENCY { get; set; }
        public Nullable<System.Guid> GUID_JOB { get; set; }
        public Nullable<double> disc_rate { get; set; }
        public string type_pay { get; set; }
        public Nullable<double> type_dis { get; set; }
        public Nullable<double> p_extra { get; set; }
        public Nullable<double> p_disc { get; set; }
        public Nullable<double> EXTEA { get; set; }
        public Nullable<double> disc { get; set; }
        public Nullable<System.Guid> STORE_GUID { get; set; }
        public string NOTE { get; set; }
        public Nullable<System.Guid> CUST { get; set; }
        public Nullable<System.Guid> PARENT_GUID { get; set; }
        public string name { get; set; }
        public int id { get; set; }
    }
}
