//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Acc_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALOUN_SESSIONS
    {
        public int ID { get; set; }
        public Nullable<int> NUMBER { get; set; }
        public string CUSTOMER { get; set; }
        public string MOBILE { get; set; }
        public string PACKAGE { get; set; }
        public string BALANCE { get; set; }
        public string COMMEMNT { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string staff { get; set; }
    }
}
