//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Acc_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class set_pos
    {
        public int id { get; set; }
        public Nullable<System.Guid> guid_user { get; set; }
        public Nullable<System.Guid> guid_cu { get; set; }
        public Nullable<System.Guid> guid_stor { get; set; }
        public Nullable<System.Guid> guid_currency { get; set; }
        public Nullable<double> val_currency { get; set; }
        public Nullable<System.Guid> guid_job { get; set; }
        public Nullable<int> show_iteme { get; set; }
    }
}
