//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Acc_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SHOW_USE
    {
        public int ID { get; set; }
        public Nullable<System.Guid> GUID_UD { get; set; }
        public Nullable<bool> FI { get; set; }
        public Nullable<bool> FI1 { get; set; }
        public Nullable<bool> FI2 { get; set; }
        public Nullable<bool> FI3 { get; set; }
        public Nullable<bool> FI4 { get; set; }
        public Nullable<bool> FI5 { get; set; }
        public Nullable<bool> FI6 { get; set; }
        public Nullable<bool> FI7 { get; set; }
        public Nullable<bool> FI8 { get; set; }
        public Nullable<bool> FI9 { get; set; }
        public Nullable<bool> FI10 { get; set; }
        public Nullable<bool> ACC { get; set; }
        public Nullable<bool> ACC1 { get; set; }
        public Nullable<bool> ACC2 { get; set; }
        public Nullable<bool> ACC3 { get; set; }
        public Nullable<bool> ACC4 { get; set; }
        public Nullable<bool> ACC5 { get; set; }
        public Nullable<bool> ACC6 { get; set; }
        public Nullable<bool> ACC7 { get; set; }
        public Nullable<bool> ACC8 { get; set; }
        public Nullable<bool> ACC9 { get; set; }
        public Nullable<bool> ACC10 { get; set; }
        public Nullable<bool> ACC11 { get; set; }
        public Nullable<bool> ACC12 { get; set; }
        public Nullable<bool> MT { get; set; }
        public Nullable<bool> MT1 { get; set; }
        public Nullable<bool> MT2 { get; set; }
        public Nullable<bool> MT3 { get; set; }
        public Nullable<bool> MT4 { get; set; }
        public Nullable<bool> MT5 { get; set; }
        public Nullable<bool> MT6 { get; set; }
        public Nullable<bool> MT7 { get; set; }
        public Nullable<bool> MT8 { get; set; }
        public Nullable<bool> MT9 { get; set; }
        public Nullable<bool> MT10 { get; set; }
        public Nullable<bool> INV { get; set; }
        public Nullable<bool> INV1 { get; set; }
        public Nullable<bool> INV2 { get; set; }
        public Nullable<bool> INV3 { get; set; }
        public Nullable<bool> INV4 { get; set; }
        public Nullable<bool> INV5 { get; set; }
        public Nullable<bool> INV6 { get; set; }
        public Nullable<bool> INV7 { get; set; }
        public Nullable<bool> INV8 { get; set; }
        public Nullable<bool> INV9 { get; set; }
        public Nullable<bool> INV10 { get; set; }
        public Nullable<bool> INV11 { get; set; }
        public Nullable<bool> INV12 { get; set; }
        public Nullable<bool> INV13 { get; set; }
        public Nullable<bool> INV14 { get; set; }
        public Nullable<bool> INV15 { get; set; }
        public Nullable<bool> EMP { get; set; }
        public Nullable<bool> EMP1 { get; set; }
        public Nullable<bool> EMP2 { get; set; }
        public Nullable<bool> EMP3 { get; set; }
        public Nullable<bool> EMP4 { get; set; }
        public Nullable<bool> EMP5 { get; set; }
        public Nullable<bool> EMP6 { get; set; }
        public Nullable<bool> EMP7 { get; set; }
        public Nullable<bool> EMP8 { get; set; }
        public Nullable<bool> EMP9 { get; set; }
        public Nullable<bool> EMP10 { get; set; }
        public Nullable<bool> REP_ACC { get; set; }
        public Nullable<bool> REP_ACC1 { get; set; }
        public Nullable<bool> REP_ACC2 { get; set; }
        public Nullable<bool> REP_ACC3 { get; set; }
        public Nullable<bool> REP_ACC4 { get; set; }
        public Nullable<bool> REP_ACC5 { get; set; }
        public Nullable<bool> REP_ACC6 { get; set; }
        public Nullable<bool> REP_ACC7 { get; set; }
        public Nullable<bool> REP_ACC8 { get; set; }
        public Nullable<bool> REP_ACC9 { get; set; }
        public Nullable<bool> REP_ACC10 { get; set; }
        public Nullable<bool> REP_MT { get; set; }
        public Nullable<bool> REP_MT1 { get; set; }
        public Nullable<bool> REP_MT2 { get; set; }
        public Nullable<bool> REP_MT3 { get; set; }
        public Nullable<bool> REP_MT4 { get; set; }
        public Nullable<bool> REP_MT5 { get; set; }
        public Nullable<bool> REP_MT6 { get; set; }
        public Nullable<bool> REP_MT7 { get; set; }
        public Nullable<bool> REP_MT8 { get; set; }
        public Nullable<bool> REP_MT9 { get; set; }
        public Nullable<bool> REP_MT10 { get; set; }
        public Nullable<bool> REP_MT11 { get; set; }
        public Nullable<bool> REP_MT12 { get; set; }
        public Nullable<bool> SETTT { get; set; }
        public Nullable<bool> SETTT1 { get; set; }
        public Nullable<bool> SETTT2 { get; set; }
        public Nullable<bool> SETTT3 { get; set; }
        public Nullable<bool> SETTT4 { get; set; }
        public Nullable<bool> SETTT5 { get; set; }
        public Nullable<bool> SETTT6 { get; set; }
        public Nullable<bool> SETTT7 { get; set; }
        public Nullable<bool> pos { get; set; }
        public Nullable<bool> daily_report { get; set; }
        public Nullable<bool> item_report { get; set; }
        public Nullable<bool> inventory_report { get; set; }
        public Nullable<bool> item_activity { get; set; }
        public Nullable<bool> define_subs { get; set; }
        public Nullable<bool> subs_register { get; set; }
        public Nullable<bool> sessino_record { get; set; }
        public Nullable<bool> subs_report { get; set; }
        public Nullable<bool> employee { get; set; }
        public Nullable<bool> customer { get; set; }
        public Nullable<bool> print_barcode { get; set; }
    }
}
