//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Acc_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Show_Items
    {
        public string NAME { get; set; }
        public string Group { get; set; }
        public Nullable<double> AVG_PRICE { get; set; }
        public string latin_name { get; set; }
        public string Company { get; set; }
        public Nullable<double> EndUser { get; set; }
        public Nullable<double> LastPrice { get; set; }
        public string TYPE_ITEME { get; set; }
        public string Is_Sales { get; set; }
        public string Status { get; set; }
        public Nullable<int> Sort { get; set; }
        public string BARCODE_1 { get; set; }
        public int ID { get; set; }
    }
}
