//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Acc_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff_Sales_tb
    {
        public int id { get; set; }
        public string Emp_Name { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public Nullable<int> Invoice_no { get; set; }
        public Nullable<double> Total { get; set; }
        public Nullable<System.Guid> Bill_Guid { get; set; }
        public Nullable<int> Number { get; set; }
        public byte[] barcode { get; set; }
    }
}
