//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Acc_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENT
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<System.DateTime> DTP { get; set; }
        public string NAME { get; set; }
        public string LASTNAME { get; set; }
        public string COMPANY { get; set; }
        public string COMPANYJOB { get; set; }
        public string COUNTRY { get; set; }
        public string CUNTRY { get; set; }
        public string STREET { get; set; }
        public string PHON { get; set; }
        public string MOB1 { get; set; }
        public string MOB2 { get; set; }
        public string MAIL { get; set; }
        public string WEB { get; set; }
        public byte[] img { get; set; }
        public string typ_e { get; set; }
        public Nullable<System.Guid> GUID_ACCOUNT { get; set; }
        public System.Guid GUID { get; set; }
        public Nullable<System.Guid> guid_user { get; set; }
        public string CARD_STUDENE { get; set; }
        public Nullable<System.DateTime> DATE_OK { get; set; }
        public Nullable<int> CLASS_ { get; set; }
        public string ID_CLASS { get; set; }
        public Nullable<int> TYP_F { get; set; }
        public Nullable<System.DateTime> DATE_F { get; set; }
        public Nullable<System.DateTime> DATE_MANG { get; set; }
        public string SCHOOL_B { get; set; }
        public string FATHER_NAME { get; set; }
        public string CARD_FATHER { get; set; }
        public string MATHER_NAME { get; set; }
        public string CARD_MATHER { get; set; }
        public string TEACHER { get; set; }
        public Nullable<double> MONY_SCHOOL { get; set; }
        public Nullable<System.DateTime> MANG_END { get; set; }
        public Nullable<System.Guid> branch_GUID { get; set; }
        public Nullable<System.DateTime> DATE_YEARE { get; set; }
        public Nullable<int> TEACHER_M { get; set; }
        public string STUDENT_STAT { get; set; }
        public string PAY_FOR { get; set; }
        public Nullable<int> ACTVE_STUDENT { get; set; }
    }
}
