//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Acc_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subs_Report_New
    {
        public int ID { get; set; }
        public string CUSTOMER { get; set; }
        public string TELE { get; set; }
        public string TYPE { get; set; }
        public Nullable<double> VALUE { get; set; }
        public Nullable<int> DISCOUNT { get; set; }
        public Nullable<System.DateTime> START { get; set; }
        public Nullable<System.DateTime> END { get; set; }
        public Nullable<double> Cash { get; set; }
        public Nullable<double> Knet { get; set; }
        public Nullable<int> count { get; set; }
        public Nullable<int> Number { get; set; }
    }
}
