//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Acc_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUBS_TYPE
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public Nullable<double> VALUE { get; set; }
        public Nullable<int> DAYS_COUNT { get; set; }
        public Nullable<int> DISCOUNT { get; set; }
        public Nullable<int> Count { get; set; }
        public string Type { get; set; }
    }
}
