//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Acc_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int id { get; set; }
        public string Midan { get; set; }
        public string Tour { get; set; }
        public Nullable<System.DateTime> Ticket_Date { get; set; }
        public Nullable<System.TimeSpan> Start_Time { get; set; }
        public Nullable<System.TimeSpan> End_Time { get; set; }
        public Nullable<double> Value { get; set; }
        public Nullable<double> cash { get; set; }
        public Nullable<double> knet { get; set; }
        public string Moblie { get; set; }
    }
}
