//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Acc_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket_Player
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public string C_ID { get; set; }
        public string SEX { get; set; }
        public string MOBILE { get; set; }
        public string Weapon { get; set; }
        public byte[] PlayerImage { get; set; }
        public byte[] C_idImage { get; set; }
        public string Status { get; set; }
    }
}
