//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Acc_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TICKET_O2
    {
        public int ID { get; set; }
        public Nullable<int> NUMBER { get; set; }
        public string user_ { get; set; }
        public string CUSTOMER { get; set; }
        public string MOBILE { get; set; }
        public string TIKET_TYPE { get; set; }
        public Nullable<double> PRICE { get; set; }
        public Nullable<double> CASH { get; set; }
        public Nullable<double> KNET { get; set; }
        public string NOTES { get; set; }
        public Nullable<double> DISCOUNT { get; set; }
        public string STATUES { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public Nullable<System.DateTime> Date_ { get; set; }
    }
}
