//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Acc_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TYPE_BILL
    {
        public int id { get; set; }
        public System.Guid GUID { get; set; }
        public string NAME { get; set; }
        public Nullable<int> NUMBER { get; set; }
        public Nullable<System.Guid> day_iteme { get; set; }
        public Nullable<System.Guid> day_disc { get; set; }
        public Nullable<System.Guid> cash_day { get; set; }
        public Nullable<System.Guid> TRAN_POS_GUID { get; set; }
        public Nullable<int> is_stock { get; set; }
        public Nullable<int> is_day { get; set; }
        public Nullable<int> pricee { get; set; }
        public Nullable<System.Guid> vat { get; set; }
        public Nullable<System.Guid> Default_Store { get; set; }
    }
}
