//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Acc_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TYPE_CASH
    {
        public System.Guid GUID { get; set; }
        public string NAME { get; set; }
        public Nullable<int> CODE { get; set; }
        public Nullable<System.Guid> CASHACCOUNT { get; set; }
        public Nullable<int> EMPLOYEE { get; set; }
    }
}
