//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Acc_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class US00_ET
    {
        public int id { get; set; }
        public Nullable<System.Guid> GUIDUSER { get; set; }
        public Nullable<System.Guid> GUID_BT { get; set; }
        public Nullable<bool> ISINSERT { get; set; }
        public Nullable<bool> ISUPDATE { get; set; }
        public Nullable<bool> ISDELETE { get; set; }
        public Nullable<bool> ISprint { get; set; }
        public Nullable<bool> ISSHOW { get; set; }
    }
}
