//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Acc_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_shoe_iteme
    {
        public System.Guid Expr1 { get; set; }
        public System.Guid GUID { get; set; }
        public string المجموعة { get; set; }
        public string اسم_المادة { get; set; }
        public string ملاحظات { get; set; }
        public Nullable<double> الرصيد { get; set; }
        public Nullable<double> avg_price { get; set; }
        public byte[] img { get; set; }
    }
}
