//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Acc_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Waiters_Report
    {
        public System.Guid GUID { get; set; }
        public string NAME { get; set; }
        public Nullable<double> PRICE { get; set; }
        public Nullable<double> QTY { get; set; }
        public Nullable<System.DateTime> Time_Punch { get; set; }
        public string Expr1 { get; set; }
        public string Waiter { get; set; }
    }
}
